layout_spectrum: 1
typography_spectrum: 0.6577061
color:
  saturation: 0.5716846
  lightness: 0.4767025
  brandStrength: 0.4928315
  rhythmicContrast: 0.5286738
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: The Native Business Playbook
